name: computeProject
channels:
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - ipywidgets
  - notebook
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - pip
  - lxml
  - simplegeneric
  - cython
  - geopandas
  - tensorflow
  - scikit-learn
  - graphviz
  - pydot
